language: php

php:
    - 7.1
    - 7.2
    - 7.3

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction

script:
    - vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover coverage.xml
    - "vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix src/ --rules=@Symfony --rules='{\"phpdoc_to_param_type\": {\"scalar_types\": false}}' --allow-risky=yes"
