language: php

php:
  - '7.1'

install:
  - composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover build/logs/clover.xml
  - vendor/bin/phpcs --ignore=vendor --standard=PSR12 .
  - vendor/bin/phpstan analyze . --level 7

after_success:
  - travis_retry php vendor/bin/php-coveralls -v